/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testSquare() {
        Shapes square = new Shapes(Shapes.Unary.SQUARE, 4);
        assertEquals(square.area(), 16, 0.000001);
    }

    @Test
    public void testRectangle() {
        Shapes rectangle = new Shapes(Shapes.Binary.RECTANGLE, 4, 6);
        assertEquals(rectangle.perimeter(), 20, 0.000001);
    }

}
